### ISSUE TITLE
what is the difference with dyad and which one to use?

### ISSUE THREAD

**Issue by KrishnaPG** [rxi/sandbird#2]
For creating a high-performance server, which one would you suggest: sandbird or dyad?

What is their primary difference?

**Comment by rxi** [comment]
Sandbird is a tiny embeddable HTTP server, where as dyad is a small library for TCP networking. Both the projects are meant for *small* servers: sandbird being suitable for things like web interfaces or debug interfaces for long-running processes; dyad for things like networked games, simple client/servers or a debug console server.

For a high-performance server you shouldn't use either library, instead check out something like [libuv](http://libuv.org/).
