### ISSUE TITLE
Exception Thrown; read acces violation, svr is nullptr

### ISSUE THREAD

**Issue by omertoast** [rxi/sandbird#6]
I found a proxy on github and when i run it, I'm getting this.
![image](https://user-images.githubusercontent.com/30231311/74433848-47704600-4e72-11ea-8ea7-fdcc1ff02f8a.png)

**Comment by rxi** [comment]
This looks like an issue external to the library -- the server pointer passed to that function is expected to be none-`NULL`. The most likely issue is that the call to `sb_new_server()` is failing as the port can't be bound and thus `NULL` is returned, it's expected that the user checks for this error case, but if that isn't happening it may eventually get passed to the function where you're encountering an issue.
